- hosts: koda
  become: yes
  vars:
    ec2_role: bastion # for datadog-agent-v6 role
    aws_region: ap-northeast-1 # for codedeploy-agent role
  roles:
    - base
    - datadog-agent-v6
    - codedeploy-agent
