- name: install required extentions and git command
  yum:
    name:
      - git
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - xz
      - xz-devel
      - libffi-devel

- name: pyenv check present
  stat:
    path: /home/{{ pyenv_user }}/.pyenv
  register: pyenv_present

- name: pyenv install
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /home/{{ pyenv_user }}/.pyenv
  when: pyenv_present.stat.exists == False
  become_user: "{{ pyenv_user }}"

- name: pyenv export
  blockinfile:
    path: /home/{{ pyenv_user }}/.bash_profile
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
      fi
  notify: pyenv reflection

- name: python install {{ pyenv_python_version }}
  shell: source /home/{{ pyenv_user }}/.bash_profile && pyenv install {{ pyenv_python_version }}
  args:
    creates: /home/{{ pyenv_user }}/.pyenv/versions/{{ pyenv_python_version }}
  become_user: "{{ pyenv_user }}"

- name: global set python {{ pyenv_python_version }}
  shell: source /home/{{ pyenv_user }}/.bash_profile && pyenv global {{ pyenv_python_version }} && pyenv rehash
  become_user: "{{ pyenv_user }}"
